### ISSUE TITLE
Error 404 - can't download Cornell's data

### ISSUE THREAD

**Issue by tgalaj** [ebruneton/clear-sky-models#1]
Hey,

when I build your project with command: "make all", everything builds fine except it can not download clear sky radiance data from Cornell University (http://www.graphics.cornell.edu/resources/clearsky/data/2013-05-27/RADIANCE - 404 error).

Do you know how I can get these data?

Best regards,
TG

**Comment by ebruneton** [comment]
It looks like the official page for the paper and the associated data has been deleted (or moved somewhere else but I can't find it). A backup is provided by one of the co-authors here: http://www.yiningkarlli.com/projects/skydomecompare/data.html
